export default {
  pages: [
    'pages/textarea/textarea',
    'pages/avatar/basic/avatar',
    'pages/avatar/circle/avatar',
    'pages/calendar/basic/calendar',
    'pages/calendar/multiple/calendar',
    'pages/calendar/maxAndMin/calendar',
    'pages/calendar/year/calendar',
    'pages/calendar/yearMultiple/calendar',
    'pages/calendar/yearMaxAndMin/calendar',
    'pages/calendar/month/calendar',
    'pages/calendar/monthMultiple/calendar',
    'pages/calendar/monthMaxAndMin/calendar',
    'pages/calendar/quarter/calendar',
    'pages/calendar/quarterMultiple/calendar',
    'pages/calendar/quarterMaxAndMin/calendar',
    'pages/radio/radio/radio',
    'pages/radio/radioGroup/radioGroup',
    'pages/floatLayout/basic/floatLayout',
    'pages/floatLayout/middle/floatLayout',
    'pages/floatLayout/follow/floatLayout',
    'pages/card/card',
    'pages/searchBar/basic/searchBar',
    'pages/searchBar/multiple/searchBar',
    'pages/searchBar/theme/searchBar',
    'pages/fixedButton/horizontal/fixedButton',
    'pages/fixedButton/horizontalCustom/fixedButton',
    'pages/fixedButton/vertical/fixedButton',
    'pages/fixedButton/verticalCustom/fixedButton',
    'pages/fixedButton/icon/fixedButton',
    'pages/upload/basic/upload',
    'pages/upload/multiple/upload',
    'pages/inputNumber/default/inputNumber',
    'pages/inputNumber/disabled/inputNumber',
    'pages/dateTimePicker/basic/dateTimePicker',
    'pages/empty/empty',
    'pages/form/edit/form',
    'pages/form/view/form',
    'pages/datePicker/singleChoice/datePicker',
    'pages/datePicker/multipleChoice/datePicker',
    'pages/datePicker/yearSingleChoice/datePicker',
    'pages/datePicker/yearMultipleChoice/datePicker',
    'pages/datePicker/yearMonthSingleChoice/datePicker',
    'pages/datePicker/yearMonthMultipleChoice/datePicker',
    'pages/datePicker/quarterSingleChoice/datePicker',
    'pages/datePicker/quarterMultipleChoice/datePicker',
    'pages/checkbox/checkbox/checkbox',
    'pages/checkbox/checkboxButton/checkboxButton',
    'pages/checkbox/checkboxGroup/checkboxGroup',
    'pages/formItemCheckboxGroup/formItemCheckboxGroup',
    'pages/formItemPicker/basic/formItemPicker',
    'pages/formItemPicker/multiple/formItemPicker',
    'pages/formItemPicker/time/formItemPicker',
    'pages/formItemPicker/region/formItemPicker',
    'pages/steps/steps',
    'pages/table/basic/table',
    'pages/table/fixed/table',
    'pages/table/sum/table',
    'pages/tabs/tabs',
    'pages/editor/editor',
    'pages/timeline/basic/timeline',
    'pages/timeline/custom/timeline',
    'pages/pageContainer/pageContainer/pageContainer',
    'pages/pageContainer/header/pageContainer',
    'pages/pageContainer/footer/pageContainer',
    'pages/pageContainer/full/pageContainer',
    'pages/section/section',
    'pages/list/list',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
    pageOrientation:"portrait"
  }
}
